### ISSUE TITLE
R: 4.0.X library(bayeos) command fails with error

### ISSUE THREAD

**Issue by oarchner** [BayCEER/BayEOS-R#3]
The library can't be used on Windows:

install.packages("bayeos", repos = "http://www.bayceer.uni-bayreuth.de/R-repository")
Installing package into ‘C:/Users/oliver/Documents/R/win-library/4.0’
(as ‘lib’ is unspecified)
trying URL 'http://www.bayceer.uni-bayreuth.de/R-repository/bin/windows/contrib/4.0/bayeos_1.4.6.zip'
Content type 'application/zip' length 135822 bytes (132 KB)
downloaded 132 KB

The downloaded binary packages are in
	C:\Users\oliver\AppData\Local\Temp\Rtmp04KFPY\downloaded_packages

**> library(bayeos)
Error: package or namespace load failed for ‘bayeos’:
 package ‘bayeos’ was installed before R 4.0.0: please re-install it**

**Comment by holzheu** [comment]
The prebuild library did not load in R 4.0. We removed these binary packages and suggest install from source:

install.packages("bayeos", repos = "http://www.bayceer.uni-bayreuth.de/R-repository", type="source")
